# Generated by Django 3.2.7 on 2022-03-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_skill_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='text',
            field=models.TextField(),
        ),
    ]
